works
cwruRobotics/rov-23 pull request #45
Opened 2023-02-03 04:52 UTC by InvincibleRMC

2023-02-03 15:31 UTC, InvincibleRMC commented
#13 and #14 should be able to use this for testing once merged

2023-02-03 21:51 UTC, benjaminwp18 requested changes

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/gui/gui/modules/task_selector.py
> +    enum = Tasks.MANUAL_CONTROL.value
Store as enum, not enum value

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/gui/gui/modules/task_selector.py
> +        if (i == 0):
Modify enum definition to use specific ints (0,1,2,3..) instead of auto, have these correspond with positions in GUI dropdown

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/gui/gui/modules/task_selector.py
> +        # TODO Should activate default state
Maybe have task selector start up in manual control & GUI start up with manual control shown on dropdown?

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/controller/package.xml
> +<?xml version="1.0"?>
Rename this package to something like ps5_controller or joy_controller to make it clear that it's a device-specific listener

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/task_selector/task_selector/control_node.py
> +import rclpy
Rename everything related to `control_node` to `manual_control_node`

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/task_selector/task_selector/control_node.py
> +    # Maybe should be ENUMS?
If we keep constants: add typing, use tabs to make things pretty
If we use ENUMs: `axes[self.JOY_BUTTONS.PAIRING_BUTTON.value]` is a pain to write, so maybe write a helper `axes_array_to_dict` or `axes_array_to_obj` that converts the axes array to a dict with descriptive names or an object with fields for each value

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/task_selector/task_selector/control_node.py
> +    def joystick_profiles(self, val: float):
I think `val * abs(val)` is equivalent to squaring: `val ** 2`, which is a heck of a lot shorter to write than `self.joystick_profiles`

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/task_selector/task_selector/control_node.py
> +            )
1 too many tabs

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/task_selector/task_selector/control_node.py
> +        self.get_logger().info('Starting Manual Control')
Add typing in this method

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/task_selector/task_selector/control_node.py
> +    def controller_callback(self, msg: Joy):
Add typing to this method

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/task_selector/task_selector/control_node.py
> +    def cancel_callback(self, goal_handle):
We should ask Eric about what this does that's different from `execute_callback` with `goal_handle.is_cancel_requested == True`

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/task_selector/task_selector/task_requestor.py
> +                                                  'manual_control')
This is Eric's fault, but these client declarations are incredibly ugly. Maybe this is better idk:
```
self.morning_action_client = \
            ActionClient(self, Example, 'say_good_morning')
```

2023-02-03 21:51 UTC, benjaminwp18 commented on surface/controller/doc/readme.md
> +Boilerplate which calls the standard Joy package
Can you say what the package is for (i.e. "gets PS5 control streaming on topic foo using message bar")

2023-02-04 21:26 UTC, benjaminwp18 approved these changes

2023-02-04 21:26 UTC, merged