Typing investigation
cwruRobotics/rov-23 pull request #48
Opened 2023-02-06 18:42 UTC by InvincibleRMC

Ben loves all my PR's so much

2023-02-08 20:48 UTC, benjaminwp18 requested changes

2023-02-08 20:48 UTC, benjaminwp18 commented on surface/gui/gui/app.py
> +    def closeEvent(self, a0: QCloseEvent):
`a0`?

2023-02-08 20:48 UTC, benjaminwp18 commented on surface/gui/gui/event_nodes/server.py
> -        self.executor = executor
Removing this leaves executor as a local var, meaning `kill_executor` can't find it
Maybe just declare the executor as self.executor from the beginning?

2023-02-08 20:48 UTC, benjaminwp18 commented on surface/gui/gui/event_nodes/server.py
> -    def spin_async(self):
I originally did the `spin_async`s for parity with `publish` and `send_request_async` in the publisher and client event nodes; that way for every event node you call the constructor to make the node, then call the specific communication function to communicate. Thoughts?

2023-02-08 20:48 UTC, benjaminwp18 commented on surface/gui/gui/event_nodes/subscriber.py
> -        self.executor = executor
I don't think `kill_executor` can see this executor now, either

2023-02-08 20:48 UTC, benjaminwp18 commented on surface/gui/gui/modules/logger.py
> -SEVERITY_LEVELS = [
agghhh my javascript brain made this monstrosity
Thank you for obliterating it

2023-02-08 20:48 UTC, benjaminwp18 commented on surface/gui/gui/modules/logger.py
> +                           ]
You have the weirdest dangling bracket style I have ever seen

2023-02-08 20:48 UTC, benjaminwp18 commented on surface/task_selector/task_selector/manual_control_node.py
> +    def execute_callback(self, goal_handle: ServerGoalHandle) -> BasicTask.Result:
It's beautiful

2023-02-08 20:48 UTC, benjaminwp18 commented on surface/task_selector/task_selector/task_requestor.py
> +        if isinstance(task_id, int):
liberatore says this is an excellent opportunity to exit early:
```python
if not isinstance(task_id, int):
     self.get_logger().fatal("task_id is not int!")
     return response
```

Also, do we need type checking coming out of a ROS interface? If we don't interpret those types as guaranteed, that's gonna mean a lot of `isinstance`

2023-02-08 20:55 UTC, InvincibleRMC commented on surface/gui/gui/app.py
> +    def closeEvent(self, a0: QCloseEvent):
When overloading a method you should use what is was called. PyQT5 called it an a0

2023-02-08 20:56 UTC, InvincibleRMC commented on surface/gui/gui/event_nodes/server.py
> -    def spin_async(self):
You want to actively make people publish and send requests
But for listeners its just asking for people to forget to call spin for no reason

2023-02-11 00:51 UTC, benjaminwp18 requested changes

2023-02-11 00:51 UTC, benjaminwp18 commented on surface/gui/gui/app.py
> +    def closeEvent(self, a0: QCloseEvent):
Add a comment so I don't change it

2023-02-11 00:51 UTC, benjaminwp18 commented on surface/task_selector/task_selector/manual_control_node.py
> +        # TODO would Service make more sense then Actions?
No; we need feedback over time
Remove this

2023-02-11 02:23 UTC, benjaminwp18 approved these changes

2023-02-11 02:26 UTC, merged