Distributed gui
cwruRobotics/rov-23 pull request #58
Opened 2023-02-25 22:43 UTC by NoahMollerstuen

Create two subclasses of App, PilotApp and OperatorApp, and create launch files for each. Each surface computer will run either the pilot gui or the operator gui but not both.

2023-02-25 23:09 UTC, benjaminwp18 requested changes
I've edited this ticket's description to include the following, so we can start doing other task specific things once this goes through:
>Decide whether operator will switch tasks for every task (e.g. taking a picture of the seagrass habitat), or whether they'll have access to general buttons for recording images/videos for later viewing. See the software column of the [task list](https://docs.google.com/spreadsheets/d/1OQpF9YHQ2OBLLKuip4RsIXiebvILBrW31Eu4gBnE0AU/edit) for tasks where we'll do something besides manual control.

I think I'm leaning toward a task selection dropdown with generalist picture taking & video recording tasks, but we should kibitz

2023-02-25 23:09 UTC, benjaminwp18 commented on surface/gui/gui/pilot_app.py
> +        self.modules.append(self.video_area)
Is it worth abstracting this to an `add_module(module, position)` method? Might make things simpler for people adding their first module.

2023-02-25 23:09 UTC, benjaminwp18 commented on surface/gui/gui/run_gui.py
> +    run_gui("pilot")
Could pass `OperatorApp` or `PilotApp` here and assign that to window in run_gui, rather than using the string & an if

2023-02-25 23:09 UTC, benjaminwp18 commented on surface/gui/gui/run_gui.py
> +def run_gui(gui_type: str):
Might as well add typing to everything in this method while we're here

2023-02-25 23:11 UTC, InvincibleRMC requested changes
Probably also want a launch all in the surface to make it easier for testing

2023-02-25 23:11 UTC, InvincibleRMC commented on surface/gui/gui/run_gui.py
> +def run_gui(gui_type: str):
Feels like this should be a super class of both apps maybe

2023-02-25 23:11 UTC, benjaminwp18 commented on surface/gui/gui/run_gui.py
> +import rclpy
Possibly move all of `run_gui.py` to `app.py`?

2023-02-26 03:20 UTC, Tazmania40 commented on surface/gui/gui/run_gui.py
> +def run_gui(gui_type: str):
Just because we want a launch all for testing, it shouldn't be combined totally because it will eventually be distributed onto 2 laptops with 2 launch files. I'd do a different launch file for each and a combined as a third

2023-02-26 18:18 UTC, NoahMollerstuen commented on surface/gui/gui/operator_app.py
> +        super().__init__("pilot_gui_node")
Yeah it should be `operator_gui_node`. Using single quotes hurts my soul but it's not in the style guide so I guess I'll make it consistent

2023-02-26 18:19 UTC, NoahMollerstuen commented on surface/gui/gui/operator_app.py
> +        self.setWindowTitle('CWRUbotix ROV 2023 - Operator')
Sure, I'll change that

2023-02-26 18:22 UTC, NoahMollerstuen commented on surface/gui/gui/pilot_app.py
> +        self.modules.append(self.video_area)
I don't think using a single grid layout for every widget makes sense, it's very restrictive. I'd rather compose `QHBoxLayout` and `QVBoxLayout`. We could abstract that one line for adding the module to the list, but I don't think the line is confusing as is.

2023-02-26 18:24 UTC, NoahMollerstuen commented on surface/gui/gui/run_gui.py
> +    run_gui("pilot")
Valid

2023-02-26 18:30 UTC, NoahMollerstuen commented on surface/gui/gui/run_gui.py
> +def run_gui(gui_type: str):
> Feels like this should be a super class of both apps maybe

Wdym by that? You want `run_gui` to be a class?

2023-02-26 18:33 UTC, NoahMollerstuen commented on surface/gui/gui/run_gui.py
> +import rclpy
I think that causes circular dependencies, also this is less confusing.

2023-02-26 19:06 UTC, InvincibleRMC requested changes
I would still like a test_launch.py for launching both guis on the same machine for testing.

2023-02-26 19:06 UTC, InvincibleRMC commented on surface/gui/gui/run_gui.py
> +import rclpy
Ben is right run_gui.py should not exist. It should be in app.py. Then have run_gui_pilot/operator in their respective app.pys.

2023-02-26 19:11 UTC, InvincibleRMC commented on surface/gui/gui/run_gui.py
> +import rclpy
you might also want it to be PilotApp().run_gui() rather than run_gui(PilotApp())

2023-02-26 19:12 UTC, NoahMollerstuen commented
> I would still like a test_launch.py for launching both guis on the same machine for testing.

I added one

2023-02-26 19:35 UTC, NoahMollerstuen commented on surface/gui/gui/run_gui.py
> +import rclpy
I moved the contents of `run_gui.py` but it's kind of jank because you can't instantiate App before initiating rclpy

2023-02-26 20:29 UTC, InvincibleRMC reviewed
Looks good

2023-02-26 20:29 UTC, InvincibleRMC approved these changes

2023-02-26 21:11 UTC, benjaminwp18 approved these changes
I think it's time to open up a task selector dropdown fixes issue
But that's not for this ticket

2023-02-26 21:12 UTC, merged