Manipulators
cwruRobotics/rov-23 pull request #70
Opened 2023-04-08 19:53 UTC by georgia-martinez

For toggling the manipulators on and off with the ps5 controller

2023-04-21 23:54 UTC, InvincibleRMC requested changes

2023-04-21 23:54 UTC, InvincibleRMC commented on pi/manipulators/launch/manip_launch.py
> +    ld = LaunchDescription()
Optional: construct LaunchDescription at end of generate_launch_description with a list of actions
We do that method in all of our other launch files

```python
manip_node = ...

return LaunchDescription([manip_node])
```

2023-04-21 23:54 UTC, InvincibleRMC commented on pi/manipulators/manipulators/i2c.py
> +    pass
Is this class necessary anymore?

2023-04-21 23:54 UTC, InvincibleRMC commented on pi/manipulators/manipulators/i2c.py
> +"""
Add note that we actually implemented the permanent solution

2023-04-21 23:54 UTC, InvincibleRMC commented on pi/manipulators/manipulators/i2c.py
Rename this file to something like `manipulator_test.py`

2023-04-21 23:54 UTC, InvincibleRMC commented on pi/manipulators/package.xml
> +  <maintainer email="case@case.edu">CWRUBotics 2022-2023</maintainer>
Update to use at least the cwrubotix address & have a better description

2023-04-21 23:54 UTC, InvincibleRMC commented on pi/manipulators/setup.py
> +    install_requires=['setuptools', 'wiringpi', 'bitstring'],
If wiringpi is still necessary, it should also be in the package.xml
If it's not, remove it here

2023-04-21 23:54 UTC, InvincibleRMC commented on pi/manipulators/setup.py
> +    description='Code for manipulators',
Better description

2023-04-21 23:54 UTC, InvincibleRMC commented on surface/task_selector/task_selector/manual_control_node.py
> +    def manip_callback(self, msg: Joy):
Add typing to variables in this method

2023-04-25 21:03 UTC, benjaminwp18 approved these changes

2023-04-25 21:09 UTC, InvincibleRMC approved these changes

2023-04-25 21:09 UTC, merged